FROM debian:testing-slim
MAINTAINER martin scharm <https://binfalse.de>

RUN echo "deb http://deb.debian.org/debian stable main" > "/etc/apt/sources.list.d/stable.list"

# install all the dependencied
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nagios-nrpe-server \
        monitoring-plugins \
        monitoring-plugins-basic \
        monitoring-plugins-common \
        monitoring-plugins-standard \
        nagios-plugins-contrib \
        curl \
        file \
        liburi-perl \
        liblwp-protocol-https-perl \
        libwww-perl \
        libhttp-cookies-perl \
        curl \
    && egrep -v "^((allowed_hosts|server_port|pid_file|include|include_dir)=|#)" /etc/nagios/nrpe.cfg | grep -v '^$' > /tmp/nrpe.cfg \
    && mv /tmp/nrpe.cfg /etc/nagios/nrpe.cfg \
    && echo "include=/etc/nagios/auto-manage.cfg" >> /etc/nagios/nrpe.cfg \
    && echo "include_dir=/etc/nagios/nrpe.d/" >> /etc/nagios/nrpe.cfg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# nrpe server cannot log to std::out, so use gospawn.  See: https://github.com/ossobv/gospawn
RUN curl -so /bin/gospawn https://junk.devs.nu/go/gospawn.upx && chmod +x /bin/gospawn

VOLUME [ "/etc/nagios/nrpe.d/", "/etc/nagios/certs/", "/usr/lib/nagios/extra/" ]
EXPOSE 5666

COPY src/nrpe-runner /

ENTRYPOINT /nrpe-runner

